# Generated by Django 3.1.3 on 2020-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Manager', 'Manager')], default='Customer', max_length=200),
        ),
    ]
