# Generated by Django 3.1.3 on 2020-12-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
