# Generated by Django 3.1.3 on 2020-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
