# Generated by Django 3.1.3 on 2020-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201213_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
